new sexy carousel for bottom card
mrogers23458/burley-home pull request #44
Opened 2023-07-17 17:36 UTC by iburley33

2023-07-17 18:05 UTC, mrogers23458 commented
conflicts

2023-07-17 18:05 UTC, mrogers23458 requested changes
resolve conflicts

2023-07-17 19:16 UTC, iburley33 commented
conflicts resolved

2023-07-17 23:21 UTC, mrogers23458 commented on ib_client_frontend/src/components/bottomcard/BottomCard.jsx
> +          <a href={link} class='bottomLink'>
use useNavigate here instead of warpping a-tags

2023-07-17 23:22 UTC, mrogers23458 commented on ib_client_frontend/src/components/slider/slider.jsx
> +    setWidth(carousel.current.scrollWidth - carousel.current.offsetWidth)
looks like this has missing deps, probably carousel.

2023-07-17 23:23 UTC, mrogers23458 commented on ib_client_frontend/src/components/slider/sliderImages.js
> +import image1 from '../../assets/imgs/1.jpg';
this seems like an unnecessary import export, why not just put them in the file where they're being used?

2023-07-17 23:23 UTC, mrogers23458 commented on ib_client_frontend/src/pages/landing/Landing.jsx
> +        <LeftCard image={placeholder} title={'GALLERY'} detail={'Our favorite summer holiday and how to style for it.'} description={'Styling Inspiration for the Fouth of July'}
looks like these are still using placeholder images?

2023-07-29 19:58 UTC, iburley33 commented on ib_client_frontend/src/pages/landing/Landing.jsx
> +        <LeftCard image={placeholder} title={'GALLERY'} detail={'Our favorite summer holiday and how to style for it.'} description={'Styling Inspiration for the Fouth of July'}
yea i dont know what images shes going to want to use ill do that stuff with her once its done

2023-07-29 20:05 UTC, iburley33 commented on ib_client_frontend/src/components/bottomcard/BottomCard.jsx
> +          <a href={link} class='bottomLink'>
done

2023-07-29 20:09 UTC, iburley33 commented on ib_client_frontend/src/components/slider/slider.jsx
> +    setWidth(carousel.current.scrollWidth - carousel.current.offsetWidth)
need more info here not sure whats missing. carousel is a self defined variable

2023-07-29 20:17 UTC, iburley33 commented on ib_client_frontend/src/components/slider/slider.jsx
> +    setWidth(carousel.current.scrollWidth - carousel.current.offsetWidth)
think i got it and fixed it

2023-07-29 20:17 UTC, iburley33 commented on ib_client_frontend/src/components/slider/sliderImages.js
> +import image1 from '../../assets/imgs/1.jpg';
fixed

2023-07-29 20:39 UTC, mrogers23458 commented on ib_client_frontend/src/components/bottomcard/BottomCard.jsx
> +  function handleNav() {
not needed can jsut use hook

2023-07-29 20:40 UTC, mrogers23458 commented on ib_client_frontend/src/components/bottomcard/BottomCard.jsx
> +            <h1 onClick={handleNav} class='bottomTitle'>{title}</h1>
```suggestion
            <h1 onClick={()=>navigate(link)} class='bottomTitle'>{title}</h1>
```

2023-07-29 20:40 UTC, mrogers23458 requested changes
small change

2023-07-31 15:47 UTC, mrogers23458 approved these changes

2023-08-02 16:52 UTC, merged